#!/usr/bin/env bash
# One-shot n8n installer for a fresh Ubuntu 22.04/24.04 VPS.
#
# Usage (run as root on the new server):
#   With a domain (recommended, auto-HTTPS via Caddy):
#     DOMAIN=n8n.yourdomain.com bash vps-bootstrap.sh
#     (point the domain's A record at this server's IP first)
#   Without a domain (quick start, plain HTTP on port 5678):
#     bash vps-bootstrap.sh
#
# Re-running is safe: it won't overwrite an existing .env.
set -euo pipefail

DOMAIN="${DOMAIN:-}"
N8N_DIR=/opt/n8n
TZ_DEFAULT="Europe/Rome"

echo "==> Installing Docker (skipped if present)..."
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi

mkdir -p "$N8N_DIR"
cd "$N8N_DIR"

if [ ! -f .env ]; then
  echo "==> Generating .env with a fresh encryption key..."
  cat > .env <<EOF
# Generated by vps-bootstrap.sh — keep this file safe; losing the key breaks saved credentials.
N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
GENERIC_TIMEZONE=${TZ_DEFAULT}
# Fill these in for the WF3 keyframe batch (Kling developer console):
KLING_ACCESS_KEY=
KLING_SECRET_KEY=
EOF
fi

if [ -n "$DOMAIN" ]; then
  echo "==> Configuring with domain: $DOMAIN (auto-HTTPS via Caddy)"
  cat > Caddyfile <<EOF
$DOMAIN {
  reverse_proxy n8n:5678
}
EOF
  cat > docker-compose.yml <<EOF
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - N8N_HOST=$DOMAIN
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://$DOMAIN/
      - N8N_PORT=5678
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
    env_file: .env
    volumes:
      - n8n_data:/home/node/.n8n

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  n8n_data:
  caddy_data:
  caddy_config:
EOF
  URL="https://$DOMAIN/"
else
  IP=$(curl -fsS ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
  echo "==> No DOMAIN set — configuring plain HTTP on port 5678 (IP: $IP)"
  cat > docker-compose.yml <<EOF
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=$IP
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://$IP:5678/
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=crypto
    env_file: .env
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
EOF
  URL="http://$IP:5678/"
fi

echo "==> Starting n8n..."
docker compose up -d

echo ""
echo "=================================================================="
echo "  n8n is starting at: $URL"
echo "  (first boot takes ~30–60s)"
echo ""
echo "  Next steps:"
echo "   1. Open the URL and create your OWNER account immediately."
echo "   2. Import the 3 workflows from the repo's n8n/ folder."
echo "   3. Add credentials (Creatomate, YouTube, Sheets, Telegram)."
echo "   4. Create an API key (Settings > n8n API) for Claude."
echo "   5. Edit /opt/n8n/.env to add Kling keys, then: docker compose restart"
echo "=================================================================="
